# Generated by Django 5.0.4 on 2024-05-17 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='locations',
            new_name='location',
        ),
    ]
