# Generated by Django 5.0.4 on 2024-05-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_phone_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='alternate_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
